---
sudo: false
language: node_js
node_js:
  - "8.9.1"
cache:
  directories:
    - "node_modules"
install:
  - "npm run develop"
script:
  - "npm run build"
  - "npm run js:test"
  - "npm run js:lint"
after_success:
  - "cat ./coverage/**/lcov.info | ./node_modules/.bin/coveralls"
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable